import _ from 'lodash';

export const activeTransaction = state => state.activeTransaction;
export const contacts = state => state.contacts;
export const currency = state => state.currency;
export const currencySymbol = state => state.currencySymbol;
export const currentEditContact = state => state.currentEditContact;
export const currentLoginToWallet = state => state.currentLoginToWallet;
export const currentNetwork = state => state.currentNetwork;
export const currentWallet = state => state.currentWallet;
export const holdings = state => state.holdings;
export const lastReceivedBlock = state => state.lastReceivedBlock;
export const lastSuccessfulRequest = state => state.lastSuccessfulRequest;
export const latestVersion = state => state.latestVersion;
export const orderBookAsks = state => _.get(state.orderbook, 'asks', []);
export const orderBookBids = state => _.get(state.orderbook, 'bids', []);
export const portfolio = state => state.portfolio;
export const recentTransactions = state => state.recentTransactions;
export const requests = state => state.requests;
export const searchTransactionFromDate = state => state.searchTransactionFromDate;
export const searchTransactionToDate = state => state.searchTransactionToDate;
export const searchTransactions = state => state.searchTransactions;
export const sendInProgress = state => state.sendInProgress;
export const showClaimGasStatus = state => state.showClaimGasStatus;
export const showPortfolioHeader = state => state.showPortfolioHeader;
export const statsToken = state => state.statsToken;
export const version = state => state.version;
export const walletToBackup = state => state.walletToBackup;
export const wallets = state => state.wallets;
